name: no-actions-rs

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build binary
        run: |
          cargo build --target=x86_64-pc-windows-gnu --verbose --release
