name: Build
on:
  push:

defaults:
  run:
    shell: bash

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions-rs/toolchain@v1.0.6
        with: 
          toolchain: stable-gnu
          profile: minimal
          default: true
      - uses: actions/checkout@v2
      - name: Build binary
        run: |
          cargo build --verbose --release
